<?php
// $Id$

function civicrm_theme_init() {
  if (arg(0) == 'civicrm') {
    global $custom_theme;
    switch (arg(1)) {
      case 'admin':
        $theme_var = 'civicrm_admin_theme';
        break;
      case 'event':
        $theme_var = 'civicrm_event_theme';
        break;
      default:
        $theme_var = 'civicrm_theme';
        break;
    }
    if (($custom_theme = variable_get($theme_var, '0')) != '0') {
      $path = drupal_get_path('module', 'system');
      drupal_add_css($path .'/admin.css', 'module');
    }
  }
  return array();
}

function civicrm_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'system_admin_theme_settings') {
    $newform['civicrm_admin_theme'] = array(
      '#type' => 'select',
      '#options' => $form['admin_theme']['#options'],
      '#title' => t('CiviCRM Administration theme'),
      '#description' => t('Choose which theme the CiviCRM administration pages should display in.'),
      '#default_value' => variable_get('civicrm_admin_theme', ''),
    );
    $newform['civicrm_event_theme'] = array(
      '#type' => 'select',
      '#options' => $form['admin_theme']['#options'],
      '#title' => t('CiviCRM Event theme'),
      '#description' => t('Choose which theme the CiviCRM event pages should display in.'),
      '#default_value' => variable_get('civicrm_event_theme', ''),
    );
    $newform['civicrm_theme'] = array(
      '#type' => 'select',
      '#options' => $form['admin_theme']['#options'],
      '#title' => t('CiviCRM User theme'),
      '#description' => t('Choose which theme the CiviCRM user pages should display in.'),
      '#default_value' => variable_get('civicrm_theme', ''),
    );
    $form = array_merge(array_slice($form, 0, 1), $newform, array_slice($form, 1));
  }
}
